spring:
  profiles: cloud,docker
  datasource:
    platform: mysql
    driver-class-name:  com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: Select 1
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl: 
      defaultZone: http://discovery:8761/eureka/
---
spring:
  profiles: cloud
eureka:
  instance: 
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.sharedservice-discovery.credentials.uri}/eureka/